In [9]:
import pandas as pd
import numpy as np

In [20]:
data = pd.read_csv('Location.csv')
loaction_data = pd.Series(data = data['Location'])
loaction_data.head()


0     Location 3
1     Location 6
2     Location 8
3    Location 26
4    Location 34
Name: Location, dtype: object

In [21]:
type(loaction_data)

pandas.core.series.Series

In [22]:
loaction_data.describe()

count            1043
unique            296
top       Location 25
freq               31
Name: Location, dtype: object

In [23]:
loaction_data.nunique()

296

In [25]:
loaction_data.unique()

array(['Location 3', 'Location 6', 'Location 8', 'Location 26',
       'Location 34', 'Location 25', 'Location 46', 'Location 156',
       'Location 21', 'Location 13', 'Location 579', 'Location 602',
       'Location 10', 'Location 44', 'Location 30', 'Location 48',
       'Location 196', 'Location 64', 'Location 91', 'Location 62',
       'Location 75', 'Location 42', 'Location 233', 'Location 95',
       'Location 78', 'Location 61', 'Location 87', 'Location 19',
       'Location 115', 'Location 350', 'Location 377', 'Location 17',
       'Location 113', 'Location 81', 'Location 58', 'Location 212',
       'Location 53', 'Location 337', 'Location 41', 'Location 632',
       'Location 73', 'Location 214', 'Location 218', 'Location 38',
       'Location 172', 'Location 197', 'Location 101', 'Location 185',
       'Location 129', 'Location 235', 'Location 142', 'Location 50',
       'Location 76', 'Location 11', 'Location 33', 'Location 22',
       'Location 145', 'Location 203', 'Loca

In [26]:
prices_per_category = pd.Series({
    'Prodcut A': 22250,
    'Prodcut B': 16600,
    'Prodcut C': 15600,
})
prices_per_category

Prodcut A    22250
Prodcut B    16600
Prodcut C    15600
dtype: int64

In [27]:
type(prices_per_category)

pandas.core.series.Series

In [28]:
prices_per_category.values

array([22250, 16600, 15600])

In [29]:
type(prices_per_category.values)

numpy.ndarray

In [30]:
prices_per_category.array

<NumpyExtensionArray>
[22250, 16600, 15600]
Length: 3, dtype: int64

In [31]:
type(prices_per_category.array)

pandas.core.arrays.numpy_.NumpyExtensionArray

In [32]:
prices_per_category.to_numpy()

array([22250, 16600, 15600])

In [33]:
type(prices_per_category.to_numpy())

numpy.ndarray

In [34]:
test_array = prices_per_category.to_numpy(dtype=float)
test_array

array([22250., 16600., 15600.])

In [35]:
numbers = pd.Series([15, 1000, 23, 45, 444])
numbers

0      15
1    1000
2      23
3      45
4     444
dtype: int64

In [39]:
numbers.sort_values()

0      15
2      23
3      45
4     444
1    1000
dtype: int64

In [40]:
loaction_data.sort_values()

637     Location 1
884     Location 1
465     Location 1
716    Location 10
623    Location 10
          ...     
482    Location 97
128    Location 97
669    Location 97
757    Location 98
372    Location 99
Name: Location, Length: 1043, dtype: object

In [43]:
loaction_data.index.name = 'Index'

In [47]:
loaction_data.index.name

'Index'

In [50]:
loaction_data.sort_values(ascending=False).head()

Index
372    Location 99
757    Location 98
128    Location 97
482    Location 97
271    Location 97
Name: Location, dtype: object

In [51]:
loaction_data_sv = loaction_data.sort_values(ascending=False)
loaction_data_sv.head()

Index
372    Location 99
757    Location 98
128    Location 97
482    Location 97
271    Location 97
Name: Location, dtype: object

In [55]:
loaction_data_sv.index

Index([ 372,  757,  128,  482,  271,  669,  612,   29,  518,  598,
       ...
        904,  912, 1010,   14,  716,  202,  298,  637,  884,  465],
      dtype='int64', name='Index', length=1043)

In [58]:
loaction_data_sv.index.sort_values()

Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
       ...
       1033, 1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042],
      dtype='int64', name='Index', length=1043)

In [60]:
loaction_data_sv.index = loaction_data_sv.index.sort_values()
loaction_data_sv.index

Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
       ...
       1033, 1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042],
      dtype='int64', name='Index', length=1043)

In [61]:
loaction_data_sv

Index
0       Location 99
1       Location 98
2       Location 97
3       Location 97
4       Location 97
           ...     
1038    Location 10
1039    Location 10
1040     Location 1
1041     Location 1
1042     Location 1
Name: Location, Length: 1043, dtype: object

In [64]:
loaction_data_sv = loaction_data.sort_values(ascending=False)
loaction_data_sv

Index
372    Location 99
757    Location 98
128    Location 97
482    Location 97
271    Location 97
          ...     
202    Location 10
298    Location 10
637     Location 1
884     Location 1
465     Location 1
Name: Location, Length: 1043, dtype: object

In [65]:
loaction_data_sv.sort_index()

Index
0        Location 3
1        Location 6
2        Location 8
3       Location 26
4       Location 34
           ...     
1038    Location 73
1039    Location 82
1040    Location 11
1041    Location 26
1042    Location 94
Name: Location, Length: 1043, dtype: object

In [66]:
loaction_data_sv

Index
372    Location 99
757    Location 98
128    Location 97
482    Location 97
271    Location 97
          ...     
202    Location 10
298    Location 10
637     Location 1
884     Location 1
465     Location 1
Name: Location, Length: 1043, dtype: object

In [68]:
loaction_data_sv = loaction_data_sv.sort_index()
loaction_data_sv

Index
0        Location 3
1        Location 6
2        Location 8
3       Location 26
4       Location 34
           ...     
1038    Location 73
1039    Location 82
1040    Location 11
1041    Location 26
1042    Location 94
Name: Location, Length: 1043, dtype: object

In [70]:
start_date_deposits = pd. Series({
'7/4/2014' : 2000,

'12/5/2014' : 2500,

'17/5/2015' : 3000,
'22/3/2016' :4500
})
start_date_deposits

7/4/2014     2000
12/5/2014    2500
17/5/2015    3000
22/3/2016    4500
dtype: int64

In [71]:
start_date_deposits['7/4/2014']

2000

In [72]:
start_date_deposits[0]

/var/folders/l7/bbtn0nwj0k7050rlqx3cgp540000gn/T/ipykernel_32029/2015198112.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  start_date_deposits[0]


2000